# Generated by Django 5.2.17 on 2026-09-10 15:53

import django.utils.timezone
import school.models
import school.security
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('learner_name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField()),
                ('entry_level', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5')], max_length=30)),
                ('current_school', models.CharField(blank=True, max_length=180)),
                ('guardian_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('consent', models.BooleanField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='School life', max_length=80)),
                ('excerpt', models.TextField(max_length=400)),
                ('body', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('location', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('introduction', models.TextField()),
                ('body', tinymce.models.HTMLField()),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Holy Family High School', max_length=150)),
                ('motto', models.CharField(default='Quid retribuam', max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image])),
                ('hero_eyebrow', models.CharField(default='Faith. Learning. Possibility.', max_length=120)),
                ('hero_title', models.CharField(default='A strong foundation. A world of possibility.', max_length=180)),
                ('hero_text', models.TextField(default='A welcoming school community where young people are encouraged to learn with purpose, grow in faith, and serve with compassion.')),
                ('hero_image', models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image])),
                ('hero_image_alt', models.CharField(blank=True, max_length=200)),
                ('about_title', models.CharField(default='An education for the whole person.', max_length=180)),
                ('about_text', models.TextField(default='At Holy Family, learning extends beyond the classroom. We believe in nurturing curious minds, building character, and helping every learner find a meaningful path forward.')),
                ('address', models.TextField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('admissions_open', models.BooleanField(default=True)),
                ('admissions_heading', models.CharField(default='Your next chapter starts here.', max_length=180)),
                ('admissions_text', models.TextField(default='Tell us about your learner. Our admissions team will review your application and contact you about the next steps.')),
                ('admissions_requirements', models.TextField(default='Complete the online enquiry with a parent or guardian. The admissions office will confirm entry requirements, supporting documents, fees, and available places.')),
                ('privacy_text', models.TextField(default='We use application details only to respond to your enquiry and assess admission. Authorised school staff can access your submission. Contact the school office to request a correction or deletion. Do not submit sensitive records through this form.')),
                ('demo_mode', models.BooleanField(default=True, help_text='Show the pitch notice. Use fictional applicant details until the school approves launch.')),
            ],
            options={
                'verbose_name': 'School settings',
                'verbose_name_plural': 'School settings',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
