# Generated by Django 5.2.17 on 2026-09-10 16:43

import school.models
import school.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional JPEG, PNG or WebP image, up to 5 MB.', upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Featured image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe the photograph for visitors using a screen reader.', max_length=200, verbose_name='Featured image description'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional JPEG, PNG or WebP image, up to 5 MB.', upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Featured image'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe the photograph for visitors using a screen reader.', max_length=200, verbose_name='Featured image description'),
        ),
        migrations.AddField(
            model_name='page',
            name='mission',
            field=models.TextField(blank=True, help_text='Optional mission statement. Shown as a separate section on this page.'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_school_values',
            field=models.BooleanField(default=False, help_text='Display the shared school values on this page. Edit their text and order in School values.'),
        ),
        migrations.AddField(
            model_name='page',
            name='vision',
            field=models.TextField(blank=True, help_text='Optional vision statement. Shown as a separate section on this page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='In Google Maps choose Share → Embed a map. Paste only the URL inside src="...", not the whole iframe. Leave blank to hide the map.', max_length=3000, validators=[school.security.validate_google_maps_embed], verbose_name='Google Maps embed URL'),
        ),
    ]
