# Generated by Django 5.2.17 on 2026-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_show_existing_about_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField(max_length=5000)),
                ('consent', models.BooleanField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_archive_label',
            field=models.CharField(default='Calendar 2025', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_archive_url',
            field=models.URLField(blank=True, default='https://docs.google.com/spreadsheets/d/1rjMktpLcZR9RqdvRMg6ffAsS97RQflXnuUp4CEKCSm8/htmlembed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading',
            field=models.CharField(default='Get in touch', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_text',
            field=models.TextField(default='Contact our school office about admissions, school life or arranging a visit.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='A Catholic school for girls, educating the whole person in the tradition of the Holy Family Sisters.'),
        ),
    ]
