# Generated by Django 5.2.17 on 2026-09-23 18:26

import school.models
import school.security
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_contactmessage_sitesettings_calendar_archive_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Department name')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Label')),
                ('value', models.CharField(help_text='For example: 1,066, 43, 98% or 60+.', max_length=40, verbose_name='Display value')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Supporting text')),
                ('icon', models.CharField(choices=[('people', 'People'), ('book', 'Learning'), ('shield', 'Achievement'), ('calendar', 'Years / dates')], default='people', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_on_school_pages', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School statistic',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Subject name')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('introduction', models.TextField(blank=True, verbose_name='Short introduction')),
                ('body', tinymce.models.HTMLField(blank=True, verbose_name='Subject content')),
                ('image', models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Featured image')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Image description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='calendar_archive_label',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='calendar_archive_url',
        ),
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('standard', 'Standard page'), ('staff', 'Staff directory'), ('curriculum', 'Subject directory')], default='standard', help_text='Directory layouts display the published records managed in the staff workspace.', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='show_statistics',
            field=models.BooleanField(default=False, help_text='Display published statistics enabled for school pages.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='statistics_text',
            field=models.TextField(blank=True, help_text='Optional introduction or date/context for your statistics.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='statistics_title',
            field=models.CharField(default='Holy Family in numbers', max_length=160),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Full name')),
                ('position', models.CharField(blank=True, max_length=160, verbose_name='Role / position')),
                ('biography', models.TextField(blank=True, verbose_name='Short biography')),
                ('image', models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Profile photo')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Photo description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('departments', models.ManyToManyField(blank=True, help_text='Select one or more departments. Leave blank to show under Other staff.', related_name='members', to='school.department')),
            ],
            options={
                'verbose_name': 'Staff profile',
                'ordering': ['order', 'title'],
            },
        ),
    ]
