# Generated by Django 5.2.17 on 2026-09-23 18:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_department_schoolstatistic_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
