# Generated by Django 5.2.17 on 2026-10-08 14:37

import school.models
import school.security
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(blank=True, default='Rooted in faith. Growing in possibility.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_history',
            field=tinymce.models.HTMLField(blank=True, verbose_name='School history'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='About header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='About header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_intro',
            field=models.TextField(blank=True, default='Discover the story and purpose of Holy Family High School.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(blank=True, verbose_name='Mission statement'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(blank=True, verbose_name='Vision statement'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Admissions header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Admissions header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_heading',
            field=models.CharField(blank=True, default='A community in motion.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Calendar header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calendar header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_intro',
            field=models.TextField(blank=True, default='School events and important dates, all in one place.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Contact header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curriculum_body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Curriculum overview'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curriculum_heading',
            field=models.CharField(blank=True, default='Curiosity today. Possibility tomorrow.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curriculum_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Curriculum header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curriculum_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Curriculum header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='curriculum_intro',
            field=models.TextField(blank=True, default='Explore the subjects that help our learners build knowledge, confidence and a sense of purpose.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_heading',
            field=models.CharField(blank=True, default='The people behind every possibility.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_image',
            field=models.ImageField(blank=True, upload_to=school.models.image_path, validators=[school.security.validate_image], verbose_name='Staff header image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Staff header image description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_intro',
            field=models.TextField(blank=True, default='Meet the teachers and school team who support our learners every day.'),
        ),
    ]
