# Generated by Django 5.2.17 on 2026-10-08 17:34

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_preserve_fixed_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Admission year'),
        ),
        migrations.AddField(
            model_name='application',
            name='boarding_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='Applying for boarding'),
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.CharField(blank=True, choices=[('Berea', 'Berea'), ('Botha-Bothe', 'Botha-Bothe'), ('Leribe', 'Leribe'), ('Mafeteng', 'Mafeteng'), ('Maseru', 'Maseru'), ("Mohale's Hoek", "Mohale's Hoek"), ('Mokhotlong', 'Mokhotlong'), ("Qacha's Nek", "Qacha's Nek"), ('Quthing', 'Quthing'), ('Thaba-Tseka', 'Thaba-Tseka'), ('Other', 'Other')], max_length=40, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='application',
            name='district_other',
            field=models.CharField(blank=True, max_length=120, verbose_name='Other district'),
        ),
        migrations.AddField(
            model_name='application',
            name='given_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='physical_address',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Physical address'),
        ),
        migrations.AddField(
            model_name='application',
            name='surname',
            field=models.CharField(blank=True, max_length=80, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_deadline',
            field=models.DateField(blank=True, default=datetime.date(2026, 10, 14), null=True, verbose_name='Application deadline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='The application fee is non-refundable.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Application fee (M)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_grade',
            field=models.CharField(choices=[('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5')], default='Grade 8', max_length=30, verbose_name='Admission grade'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_interview_date',
            field=models.DateField(blank=True, default=datetime.date(2026, 10, 17), null=True, verbose_name='Interview date'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_interview_location',
            field=models.CharField(blank=True, default='Holy Family High School', max_length=180, verbose_name='Interview venue'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_interview_subjects',
            field=models.TextField(blank=True, default='English language, Sesotho, Science and Maths', verbose_name='Interview subjects'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_interview_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), help_text='Local school time in Lesotho.', null=True, verbose_name='Interview time'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_merchant_number',
            field=models.CharField(default='5184', max_length=30, verbose_name='School merchant number'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_payment_method',
            field=models.CharField(default='M-pesa', max_length=80, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_stationery_note',
            field=models.TextField(blank=True, default='Stationery will be provided. Bring a pen, pencil and mathematical instruments.', verbose_name='Stationery instructions'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_year',
            field=models.PositiveSmallIntegerField(default=2027, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Admission year'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='entry_level',
            field=models.CharField(choices=[('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='learner_name',
            field=models.CharField(max_length=200),
        ),
    ]
