# Generated by Django 5.2.17 on 2026-10-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_application_application_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='date_from',
            field=models.DateField(blank=True, help_text='Optional. Add the start date only if it is known.', null=True, verbose_name='At Holy Family from'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='honorific',
            field=models.CharField(blank=True, help_text='Optional, for example Mrs, Mr or Sr. Leave blank if already included in the full names.', max_length=40, verbose_name='Title / honorific'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Select one or more departments. Leave blank to show under School team.', related_name='members', to='school.department'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Full names'),
        ),
    ]
