# Generated by Django 5.2.17 on 2026-10-08 18:39

from django.db import migrations, models


COPY_UPDATES = {
    'hero_text': {
        'A welcoming school community where young people are encouraged to learn with purpose, grow in faith, and serve with compassion.': 'A place to grow in knowledge, faith and confidence. Discover your strengths, follow your curiosity and shape your future at Holy Family.',
        'Educating girls physically, morally and intellectually, and empowering them to occupy all spheres of life.': 'Grow in knowledge, faith and confidence. At Holy Family, you can discover your strengths and prepare to contribute to every sphere of life.',
    },
    'curriculum_intro': {
        'Explore the subjects that help our learners build knowledge, confidence and a sense of purpose.': 'Explore the subjects that help you build knowledge, confidence and a sense of purpose.',
    },
    'staff_intro': {
        'Meet the teachers and school team who support our learners every day.': 'Find your department and meet the teachers and school team who support you every day.',
        'Meet the people who lead, teach and support our school community.': 'Meet the people who teach, guide and support you at Holy Family.',
    },
    'admissions_text': {
        'Tell us about your learner. Our admissions team will review your application and contact you about the next steps.': 'Take the next step in your learning journey. Complete your application with a parent or guardian, and our admissions team will guide you through what comes next.',
    },
    'admissions_requirements': {
        'Complete the online enquiry with a parent or guardian. The admissions office will confirm entry requirements, supporting documents, fees, and available places.': 'Complete your application with a parent or guardian. Contact the admissions office if you need help with entry requirements, supporting documents or payment.',
    },
}


def refresh_default_copy(apps, schema_editor):
    # Match recognised starter text only: preserve all independently edited content.
    sites = apps.get_model('school', 'SiteSettings').objects.using(schema_editor.connection.alias)
    for field, replacements in COPY_UPDATES.items():
        for previous, replacement in replacements.items():
            sites.filter(**{field: previous}).update(**{field: replacement})
    apps.get_model('school', 'Page').objects.using(schema_editor.connection.alias).filter(
        slug__in=['our-staff', 'staff'],
        introduction='Meet the people who lead, teach and support our school community.',
    ).update(introduction='Meet the people who teach, guide and support you at Holy Family.')


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_staffmember_date_from_staffmember_honorific_and_more'),
    ]

    operations = [
        migrations.RunPython(refresh_default_copy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sitesettings',
            name='admissions_requirements',
            field=models.TextField(default='Complete your application with a parent or guardian. Contact the admissions office if you need help with entry requirements, supporting documents or payment.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admissions_text',
            field=models.TextField(default='Take the next step in your learning journey. Complete your application with a parent or guardian, and our admissions team will guide you through what comes next.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='curriculum_intro',
            field=models.TextField(blank=True, default='Explore the subjects that help you build knowledge, confidence and a sense of purpose.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_text',
            field=models.TextField(default='A place to grow in knowledge, faith and confidence. Discover your strengths, follow your curiosity and shape your future at Holy Family.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='staff_intro',
            field=models.TextField(blank=True, default='Find your department and meet the teachers and school team who support you every day.'),
        ),
    ]
